
ignored = ["google.golang.org/appengine*"]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  branch = "master"
  name = "code.gitea.io/git"

[[constraint]]
  branch = "master"
  name = "code.gitea.io/sdk"

[[constraint]]
  revision = "05d86ea8f6e30456949f612cf68cf4a27ce8c9c5"
  name = "github.com/blevesearch/bleve"

[[constraint]]
  revision = "12dd70caea0268ac0d6c2707d0611ef601e7c64e"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  revision = "2bf8f2a19ec09c670e931282edfe6567f6be21c9"
  name = "golang.org/x/text"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[override]]
  name = "github.com/go-xorm/xorm"
  revision = "a6300f2a45e05a8f75f00a1d6188049fe7851915"

[[override]]
  name = "github.com/go-xorm/builder"
  version = "0.3.3"

[[override]]
  name = "github.com/go-sql-driver/mysql"
  revision = "c45f530f8e7fe40f4687eaa50d0c8c5f1b66f9e0"

[[override]]
  name = "github.com/mattn/go-sqlite3"
  revision = "c7c4067b79cc51e6dfdcef5c702e74b1e0fa7c75"

[[override]]
  name = "github.com/gorilla/mux"
  revision = "757bef944d0f21880861c2dd9c871ca543023cba"

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.1"

[[constraint]]
  name = "github.com/lafriks/xormstore"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/lunny/dingtalk_webhook"

[[constraint]]
  name = "github.com/markbates/goth"
  version = "1.47.2"

[[constraint]]
  branch = "master"
  name = "github.com/mcuadros/go-version"

[[constraint]]
  branch = "master"
  name = "github.com/russross/blackfriday"

[[constraint]]
  branch = "master"
  name = "github.com/tstranex/u2f"

[[constraint]]
  name = "gopkg.in/editorconfig/editorconfig-core-go.v1"
  version = "1.2.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/gomail.v2"

[[constraint]]
  name = "gopkg.in/ini.v1"
  version = "1.31.1"

[[constraint]]
  name = "gopkg.in/ldap.v3"
  version = "3.0.1"

[[constraint]]
  name = "gopkg.in/macaron.v1"
  version = "1.2.4"

[[constraint]]
  name = "gopkg.in/testfixtures.v2"
  version = "2.0.0"

[[override]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0"

[[constraint]]
  name = "github.com/mvdan/xurls"
  version = "2.0.0"
